### ISSUE TITLE
Support the `GCE_METADATA_HOST` environment variable

### ISSUE THREAD

**Issue by matheuscscp** [matheuscscp/gke-metadata-server#350]
The environment variable `GCE_METADATA_HOST` can redirect connections without messing with the kernel or the network stack, but is apparently not a standard:

https://github.com/googleapis/google-cloud-go/blob/cd894f8aea935c43a6c5625c2fd66b132a9b2f8b/compute/metadata/metadata.go#L41-L46

Nevertheless, it seems to be supported for example by Google's Go libraries, as the link above shows.

The best way to support it would be by supporting a routing mode that doesn't do anything, e.g. `None`:

```
node.gke-metadata-server.matheuscscp.io/routingMode: None
```

The pod configuration would look like this:

```yaml
spec:
  containers:
  - name: ...
    ...
    env:
    - name: HOST_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: GKE_METADATA_SERVER_PORT
      value: "8080"
```

Then on startup, the pod must set the environment variable `GCE_METADATA_HOST` to `${HOST_IP}:${GKE_METADATA_SERVER_PORT}`. Go example:

```go
package main

func init() {
	host := os.Getenv("HOST_IP")
	port := os.Getenv("GKE_METADATA_SERVER_PORT")
	os.Setenv("GCE_METADATA_HOST", fmt.Sprintf("%s:%s", host, port))
}
```
